"""Gene alias lookup sourced from the HGNC complete dataset.

Data source: https://www.genenames.org/download/statistics-and-files/
Generated by: src/data/etl_hgnc.py

GENE_ALIASES maps alias/previous symbol -> HGNC approved symbol.
SKIP_TARGETS contains GDSC2 PUTATIVE_TARGET values that are pharmacological
class descriptors (not gene names) and should be excluded from gene-level DB queries.

To refresh: PYTHONPATH=. python src/data/etl_hgnc.py
"""
import json
from pathlib import Path

_ALIASES_FILE = Path("src/data/raw/hgnc/gene_aliases.json")
_SKIP_FILE    = Path("src/data/raw/hgnc/skip_targets.json")


def _load_aliases() -> dict[str, str | list[str]]:
    if not _ALIASES_FILE.exists():
        raise FileNotFoundError(
            f"{_ALIASES_FILE} not found. "
            "Run: PYTHONPATH=. python src/data/etl_hgnc.py"
        )
    return json.loads(_ALIASES_FILE.read_text())


def _load_skip_targets() -> set[str]:
    if not _SKIP_FILE.exists():
        return set()
    return set(json.loads(_SKIP_FILE.read_text()))


GENE_ALIASES: dict[str, str | list[str]] = _load_aliases()
SKIP_TARGETS: set[str] = _load_skip_targets()
